const primary = "#0A84FF";
const secondary = "#30D158";
const accent = "#5E5CE6";
const danger = "#FF453A";

export default {
  light: {
    text: "#1C1C1E",
    textSecondary: "#6C6C70",
    textTertiary: "#AEAEB2",
    background: "#F2F2F7",
    backgroundSecondary: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceSecondary: "#F2F2F7",
    border: "rgba(60, 60, 67, 0.12)",
    tint: primary,
    primary,
    secondary,
    accent,
    danger,
    tabIconDefault: "#8E8E93",
    tabIconSelected: primary,
    messageSent: primary,
    messageReceived: "#E5E5EA",
    messageTextSent: "#FFFFFF",
    messageTextReceived: "#1C1C1E",
    broadcastAccent: accent,
    checkInGreen: secondary,
    audioAccent: "#FF9F0A",
    shadow: "rgba(0,0,0,0.08)",
  },
  dark: {
    text: "#FFFFFF",
    textSecondary: "#EBEBF5",
    textTertiary: "#636366",
    background: "#000000",
    backgroundSecondary: "#1C1C1E",
    surface: "#1C1C1E",
    surfaceSecondary: "#2C2C2E",
    border: "rgba(255, 255, 255, 0.1)",
    tint: primary,
    primary,
    secondary,
    accent,
    danger,
    tabIconDefault: "#636366",
    tabIconSelected: primary,
    messageSent: primary,
    messageReceived: "#2C2C2E",
    messageTextSent: "#FFFFFF",
    messageTextReceived: "#FFFFFF",
    broadcastAccent: accent,
    checkInGreen: secondary,
    audioAccent: "#FF9F0A",
    shadow: "rgba(0,0,0,0.4)",
  },
};
