uploads = []

[[generated]]
id = "f4SNkswSeGb7PDW-ugNdf"
uri = "file://artifacts/zivr-deck/public/hero-encryption.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LE9Abjp_fb-LAKPZQWVED"
uri = "file://artifacts/zivr-deck/public/hero-messaging.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "gBArXpBRMtX9DB8EsdLFs"
uri = "file://.local/outputs/ZIVR-App-Deck.pdf"
type = "pdf"
title = "ZIVR App Deck (PDF)"
